In [21]:
import numpy as np 

raw_data = np.arange(20)
print(f"raw data:{raw_data}")

raw data:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Task1:Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [22]:

task1 = raw_data.copy()
task1[3:9] *= -1

print(f"solution: {task1}")

solution: [ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15 16 17 18 19]


Task2:Заменить максимальный элемент случайного массива на 0

In [23]:
task2 = raw_data.copy()

task2[task2.argmax()] = 0
print(f"Solution: {task2}")

Solution: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18  0]


 Task3: Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [29]:
import numpy as np
import itertools

# 1. Setup Data
data = np.arange(4) 
side = int(np.sqrt(data.size))
matrix = data.reshape(side, side)

def get_filtered_pairs(arr):
    rows, cols = arr.shape
    
    # We avoid the 'list()' function entirely here:
    coords = [p for p in itertools.product(range(rows), range(cols))]
    
    results = []
    
    # Compare every coordinate pair
    for (r1, c1), (r2, c2) in itertools.permutations(coords, 2):
        # Skip if they share a row or share a column
        if r1 == r2 or c1 == c2:
            continue
            
        results.append([arr[r1, c1], arr[r2, c2]])
        
    return results

# 2. Execute
final_result = get_filtered_pairs(matrix)

print("Matrix:")
print(matrix)
print("\nValid Pairs (Diagonal neighbors only):")
print(final_result)

Matrix:
[[0 1]
 [2 3]]

Valid Pairs (Diagonal neighbors only):
[[np.int64(0), np.int64(3)], [np.int64(1), np.int64(2)], [np.int64(2), np.int64(1)], [np.int64(3), np.int64(0)]]


TASK4: Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [31]:
import numpy as np

A = np.array([[7, 3, 5], [1, 1, 7], [8, 0, 8],[9,5,3]]) # Sample from your output
B = np.array([[5, 8], [9, 5]])

final_results = []

for row in A:
    matches_B0 = np.intersect1d(row, B[0])
    matches_B1 = np.intersect1d(row, B[1])
    
    if matches_B0.size > 0 and matches_B1.size > 0:
        
        all_matches = np.union1d(matches_B0, matches_B1)
        
        if all_matches.size >= 2:
            final_results.append(row)

result = np.array(final_results)
print("Strict Matching Rows:")
print(result)

Strict Matching Rows:
[[9 5 3]]


TASK 5: Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [32]:
A = np.array([  [1, 1, 1],
                [1, 1, 7], 
                [8, 0, 8],
                [9, 5, 3],
                [2, 5, 3],
                [5, 5, 6],
                [2, 2, 2],
                [5, 5, 3],
                [1, 1, 1],
                [1, 1, 1],
                ]) # Sample from your output

masks = []

for i in range(len(A)):
    if (A[i] == A[i][0]).all():
        masks.append(False)
    else:
        masks.append(True)

print(A[masks])


[[1 1 7]
 [8 0 8]
 [9 5 3]
 [2 5 3]
 [5 5 6]
 [5 5 3]]


6. Дан двумерный массив. Удалить те строки, которые повторяются

In [33]:
B = np.array([[5, 8],[9, 5],[6, 8], [9, 5]])
unique_B = np.unique(B, axis=0)
print(unique_B)


[[5 8]
 [6 8]
 [9 5]]


Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).

Замечание 1. Можно считать, что все указанные объекты непустые (к примеру, в задаче 1 на диагонали матрицы есть ненулевые элементы).

Замечание 2. Для большинства задач решение занимает не больше 1-2 строк.

Задача 1: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.
Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [34]:
import math
Y = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
X = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]

#sol1

sol1 = np.diag(Y)
rez = sol1[sol1 != 0].prod()
print(f"sol1:{rez}")

#sol2
rows,cols = Y.shape
changed = False
product = 1
if rows > cols:
    temp = rows
else:
    temp = cols
set = []
for i in range(temp-1):
    if X[i][i] != 0:
        product *= X[i][i]
        changed = True
        



print(f"sol2:{product}")

sol1:3
sol2:3


Задача 2: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.
Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [35]:
#sol1
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]

def task2(x,y):

    if(len(x) != len(y)):
        print("NO")
        return

    a = b = {''}
    a.clear()
    b.clear()

    for number in y:
        b.add(number)

    for number in x:
        a.add(number)
        

    print(a == b)
    return a == b 

task2(x,y)
#sol2
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

print(np.array_equal(np.sort(x), np.sort(y)))



True
True


Задача 3: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [ ]:
#sol1
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
max = -99999

for i in range(len(x) - 1):
    if(x[i] == 0 and i < len(x) - 1):
        if x[i + 1] > max:
            max = x[i + 1]

print(max)

mask = (x[:-1] == 0)
candidates = x[1:][mask]

#sol2
x = np.array(x) 

mask = (x[:-1] == 0)
candidates = x[1:][mask]

if candidates.size > 0:
    result = candidates.max()
else:
    result = None

print(result)


5
5


Задача 4: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.
Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [37]:
x = np.array([2, 2, 2, 3, 3, 3, 5]) 

currElem = None
amount = 0
elem_array = []
step_array = []


for number in x:
    if currElem != number:
        if(amount > 0):
            elem_array.append(currElem)
            step_array.append(amount)

        currElem = number
        amount = 1
    else:
        amount += 1

if(amount > 0):
    elem_array.append(currElem)
    step_array.append(amount)

list = [int(x) for x in elem_array]
print(list)
print(step_array)

#sol2

x = np.array([2, 2, 2, 3, 3, 3, 5])

# This one function replaces your entire loop
elements, counts = np.unique(x, return_counts=True)

# Convert to standard Python ints to avoid the "np.int64" labels
elem_list = elements.tolist()
step_list = counts.tolist()

print(elem_list) # [2, 3, 5]
print(step_list) # [3, 3, 1]


[2, 3, 5]
[3, 3, 1]
[2, 3, 5]
[3, 3, 1]


Задача 5: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [38]:
import numpy as np
from scipy.spatial.distance import cdist
import time

X = np.random.rand(500, 3)
Y = np.random.rand(400, 3)

# --- Method 1: NumPy Broadcasting ---
start_np = time.time()

# We change X from (500, 3) to (500, 1, 3)
# This forces NumPy to compare each X with every Y
dists_np = np.sqrt(np.sum((X[:, np.newaxis, :] - Y[np.newaxis, :, :])**2, axis=2))

end_np = time.time()

# --- Method 2: Scipy cdist ---
start_scipy = time.time()
dists_scipy = cdist(X, Y, metric='euclidean')
end_scipy = time.time()

print(f"NumPy time: {end_np - start_np:.5f}s")
print(f"Scipy time: {end_scipy - start_scipy:.5f}s")

print("Results match:", np.allclose(dists_np, dists_scipy))

NumPy time: 0.00899s
Scipy time: 0.00122s
Results match: True


Задача 6: CrunchieMunchies *
Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием CrunchieMunchies.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши СrunchieMunchies - самый здоровый выбор для потребителей

Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [39]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
print(calorie_stats)

[ 70. 120.  70.  50. 110. 110. 110. 130.  90.  90. 120. 110. 120. 110.
 110. 110. 100. 110. 110. 110. 100. 110. 100. 100. 110. 110. 100. 120.
 120. 110. 100. 110. 100. 110. 120. 120. 110. 110. 110. 140. 110. 100.
 110. 100. 150. 150. 160. 100. 120. 140.  90. 130. 120. 100.  50.  50.
 100. 100. 120. 100.  90. 110. 110.  80.  90.  90. 110. 110.  90. 110.
 140. 100. 110. 110. 100. 100. 110.]


В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

In [40]:
average_calories = np.mean(calorie_stats)
print(average_calories)

106.88311688311688


Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.
Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [41]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.
Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [42]:
median_calories = np.median(calorie_stats_sorted)
print(median_calories)

110.0


В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.
Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [43]:
nth_percentile = 0

# We check every percentile from 1 to 100
for i in range(1, 101):
    percentile_value = np.percentile(calorie_stats, i)
    if percentile_value > 60:
        nth_percentile = i
        break

print(f"The lowest percentile greater than 60 calories is: {nth_percentile}")

The lowest percentile greater than 60 calories is: 4


Task 6: Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.
Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [44]:
more_calories = np.mean(calorie_stats > 60) * 100

print(more_calories)

96.1038961038961


In [4]:
# Stacking arrays vertically
import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9]])
stacked_vertically = np.vstack((arr1, arr2))
print(stacked_vertically)
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

# Stacking arrays horizontally
arr3 = np.array([[7, 8], [9, 10]])
stacked_horizontally = np.hstack((arr1, arr3))
print(stacked_horizontally)
# [[ 1  2  3  7  8]
#  [ 4  5  6  9 10]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [5]:
names = np.array(['T-Shirt', 'Jeans', 'Hat'])
prices = np.array([20, 50, 10])

# Get the instructions to sort by price
sort_order = np.argsort(prices) 
# sort_order is now [2, 0, 1] (because 10 is smallest, then 20, then 50)

# Apply those instructions to the Names
print(names[sort_order]) 
# Result: ['Hat', 'T-Shirt', 'Jeans']

['Hat' 'T-Shirt' 'Jeans']


In [7]:
import numpy as np

# Data
names = np.array(['Alice', 'Bob', 'Charlie', 'David'])
experience = np.array([5, 2, 5, 1])  # Years
scores = np.array([80, 90, 80, 70])  # Test result

# We want Primary Sort: Scores (Descending)
# Secondary Sort (Tie-breaker): Experience
# Note: lexsort sorts in ascending order, so we use - to flip numbers for descending
indices = np.lexsort((experience, scores)) 

print(f"Indices: {indices}")
print(f"Sorted Names: {names[indices]}")

Indices: [3 0 2 1]
Sorted Names: ['David' 'Alice' 'Charlie' 'Bob']


In [8]:

# A 3x3 grid representing different sections of a factory floor
# The numbers are the status codes reported by sensors
factory_floor = np.array([
    [100, 404, 100],
    [100, 100, 505],
    [404, 100, 100]
])

# Our list of "Danger" codes
critical_errors = [404, 505]

# 1. Generate the mask (The "Logic" step)
# This keeps the 3x3 shape!
error_mask = np.isin(factory_floor, critical_errors)

print("--- Error Mask (Logic) ---")
print(error_mask)
# Result: 
# [[False  True False]
#  [False False  True]
#  [ True False False]]

# 2. Use the mask to extract only the bad values
# (This will flatten the result because the output size is unknown)
found_errors = factory_floor[error_mask]
print("\n--- Specific Error Codes Found ---")
print(found_errors) # [404, 505, 404]

# 3. Use the mask to "Clean" the data
# Let's replace all errors with -1 so we can ignore them in calculations
clean_floor = np.where(error_mask, -1, factory_floor)
print("\n--- Cleaned Factory Map ---")
print(clean_floor)

--- Error Mask (Logic) ---
[[False  True False]
 [False False  True]
 [ True False False]]

--- Specific Error Codes Found ---
[404 505 404]

--- Cleaned Factory Map ---
[[100  -1 100]
 [100 100  -1]
 [ -1 100 100]]


In [14]:
# Data
students = np.array(["Alice", "Bob", "Charlie", "David", "Eve"])
scores = np.array([82, 95, 70, 99, 88])

# We want the students at index 3, 1, and 4 (David, Bob, and Eve)
# Note: We pass a LIST of integers as the index
vip_indices = [3, 1, 4]

# 1. Advanced Indexing with Integers
vip_names = students[vip_indices]
vip_scores = scores[vip_indices]

print("--- The VIPs ---")
print(vip_names)  
# Result: ['David' 'Bob' 'Eve'] (Order is preserved from our list!)

print(vip_scores) 
# Result: [99 95 88]

--- The VIPs ---
['David' 'Bob' 'Eve']
[99 95 88]


In [9]:
# union
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 3, 4, 5])
union = np.union1d(arr1, arr2)
print(union)  
# [1 2 3 4 5]

# intersection
intersection = np.intersect1d(arr1, arr2)
print(intersection)  
# [2 3]

# Set Difference
difference = np.setdiff1d(arr1, arr2)
print(difference)  
# [1]

# Symmetric Difference
symmetric_difference = np.setxor1d(arr1, arr2)
print(symmetric_difference)  
# [1 4 5]

[1 2 3 4 5]
[2 3]
[1]
[1 4 5]


In [10]:

scores = np.array([85, 42, 90, 55, 30])

# Scenario A: Replace values
# Logic: If score < 50, replace with 0, otherwise keep original score
cleaned_scores = np.where(scores < 50, 0, scores)
print(f"Cleaned: {cleaned_scores}") 
# Output: [85  0 90 55  0]

# Scenario B: Find locations (indices)
# If you don't provide 'x' and 'y', it returns the addresses
fail_indices = np.where(scores < 50)
print(f"Indices of fails: {fail_indices[0]}") 
# Output: [1, 4]

Cleaned: [85  0 90 55  0]
Indices of fails: [1 4]


In [ ]:


# 3x3 grid of temperatures
temps = np.array([
    [22.5, 23.1, 22.8],
    [25.0, 99.9, 24.2],  # Note the 99.9!
    [21.9, 22.0, 22.2]
])

# ANY: Is anything over 90 degrees?
is_danger = np.any(temps > 90)
print(f"Is there a danger? {is_danger}") 
# Output: True

# ALL: Is the whole factory under 30 degrees?
is_safe = np.all(temps < 30)
print(f"Is everything safe? {is_safe}") 
# Output: False

Is there a danger? True
Is everything safe? False
